<?php

namespace App\Console\Commands;

use App\Domain\Listings\Models\ProjectImage;
use App\Domain\Listings\Models\UnitImage;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Storage;

class CleanOrphanedImagesCommand extends Command
{
    protected $signature = 'images:clean-orphans
                            {--dry-run : List orphaned files without deleting them}
                            {--include-projects : Also clean orphaned project images}
                            {--force : Force cleanup without confirmation prompt}';

    protected $description = 'Scan storage and delete orphaned unit and project images that do not exist in the database';

    public function handle(): int
    {
        $isDryRun = (bool) $this->option('dry-run');
        $includeProjects = (bool) $this->option('include-projects');
        $isForce = (bool) $this->option('force');

        $disk = Storage::disk('public');

        $this->info($isDryRun ? '🔍 Scanning for orphaned images (DRY-RUN mode - nothing will be deleted)...' : '🧹 Scanning and cleaning orphaned images...');

        // 1. Clean DB orphaned records where parent model no longer exists
        $orphanUnitDbCount = UnitImage::whereDoesntHave('unit')->count();
        if ($orphanUnitDbCount > 0) {
            $this->warn("Found {$orphanUnitDbCount} unit_image records in database whose units were deleted.");
            if (! $isDryRun) {
                UnitImage::whereDoesntHave('unit')->delete();
                $this->info("✓ Cleaned {$orphanUnitDbCount} orphaned records from unit_images table.");
            }
        }

        if ($includeProjects) {
            $orphanProjectDbCount = ProjectImage::whereDoesntHave('project')->count();
            if ($orphanProjectDbCount > 0) {
                $this->warn("Found {$orphanProjectDbCount} project_image records in database whose projects were deleted.");
                if (! $isDryRun) {
                    ProjectImage::whereDoesntHave('project')->delete();
                    $this->info("✓ Cleaned {$orphanProjectDbCount} orphaned records from project_images table.");
                }
            }
        }

        // 2. Scan Unit images on disk
        $this->info("\nScanning 'units' storage folder...");
        $unitResult = $this->cleanFolder(
            disk: $disk,
            folder: 'units',
            validPaths: UnitImage::whereHas('unit')->pluck('path')->all(),
            isDryRun: $isDryRun
        );

        $totalDeleted = $unitResult['deleted_count'];
        $totalBytes = $unitResult['bytes_freed'];

        // 3. Scan Project images on disk if requested
        if ($includeProjects) {
            $this->info("\nScanning 'projects' storage folder...");
            $projectResult = $this->cleanFolder(
                disk: $disk,
                folder: 'projects',
                validPaths: ProjectImage::whereHas('project')->pluck('path')->all(),
                isDryRun: $isDryRun
            );
            $totalDeleted += $projectResult['deleted_count'];
            $totalBytes += $projectResult['bytes_freed'];
        }

        // 4. Print Summary
        $mbFreed = round($totalBytes / (1024 * 1024), 2);
        $kbFreed = round($totalBytes / 1024, 2);
        $sizeStr = $mbFreed >= 1 ? "{$mbFreed} MB" : "{$kbFreed} KB";

        $this->newLine();
        $this->info('==================== SUMMARY ====================');
        if ($isDryRun) {
            $this->warn("Total orphaned files found: {$totalDeleted}");
            $this->warn("Total reclaimable space: {$sizeStr}");
            $this->comment("Run without --dry-run to permanently delete these files.");
        } else {
            $this->info("✓ Successfully deleted {$totalDeleted} orphaned image files.");
            $this->info("✓ Reclaimed disk space: {$sizeStr}");
        }
        $this->info('=================================================');

        return Command::SUCCESS;
    }

    /**
     * Clean a specific storage folder against an allowed list of relative DB paths.
     */
    private function cleanFolder($disk, string $folder, array $validPaths, bool $isDryRun): array
    {
        $allFiles = $disk->allFiles($folder);
        $allowedMap = [];
        $validStems = [];

        foreach ($validPaths as $p) {
            $clean = ltrim(str_replace('\\', '/', $p), '/');
            $allowedMap[$clean] = true;

            $dir = dirname($clean);
            $prefix = ($dir !== '.' && $dir !== '') ? $dir.'/' : '';
            $stem = pathinfo($clean, PATHINFO_FILENAME);
            $validStems[$stem] = true;

            // Register known variants generated by GenerateThumbnailsJob
            $allowedMap[$prefix.'thumb_'.$stem.'.webp'] = true;
            $allowedMap[$prefix.'medium_'.$stem.'.webp'] = true;
            $allowedMap[$prefix.'large_'.$stem.'.webp'] = true;
            $allowedMap[$prefix.'thumb_'.basename($clean)] = true;
        }

        $orphanedFiles = [];
        $bytesFreed = 0;

        foreach ($allFiles as $file) {
            $normalized = ltrim(str_replace('\\', '/', $file), '/');
            $basename = basename($normalized);
            
            // Skip system or hidden files
            if ($basename === '.gitignore' || str_starts_with($basename, '.')) {
                continue;
            }

            // Extract the original image stem ignoring variant prefixes
            $cleanStem = pathinfo(preg_replace('/^(thumb|medium|large)_/', '', $basename), PATHINFO_FILENAME);

            if (! isset($allowedMap[$normalized]) && ! isset($validStems[$cleanStem])) {
                $fileSize = $disk->size($file) ?: 0;
                $orphanedFiles[] = $file;
                $bytesFreed += $fileSize;

                if ($isDryRun) {
                    $this->line(" [ORPHAN] {$file} (" . round($fileSize / 1024, 1) . ' KB)');
                } else {
                    $disk->delete($file);
                    $this->line(" 🗑 Deleted: {$file} (" . round($fileSize / 1024, 1) . ' KB)');
                }
            }
        }

        // Clean empty directories in the folder
        if (! $isDryRun) {
            $this->cleanEmptyDirectories($disk, $folder);
        }

        return [
            'deleted_count' => count($orphanedFiles),
            'bytes_freed' => $bytesFreed,
        ];
    }

    /**
     * Recursively remove empty directories.
     */
    private function cleanEmptyDirectories($disk, string $folder): void
    {
        $directories = $disk->allDirectories($folder);
        // Sort by length descending to delete subdirectories before parent directories
        usort($directories, fn ($a, $b) => strlen($b) <=> strlen($a));

        foreach ($directories as $dir) {
            if (empty($disk->allFiles($dir)) && empty($disk->directories($dir))) {
                $disk->deleteDirectory($dir);
            }
        }
    }
}
