<?php
return [
            [
                'name_ar' => 'الشيخ زايد',
                'name_en' => 'Sheikh Zayed City',
                'slug' => 'sheikh-zayed',
                'sort_order' => 1,
                'latitude' => '30.0488',
                'longitude' => '30.9936',
                'address_ar' => 'مدينة الشيخ زايد، محافظة الجيزة، مصر',
                'address_en' => 'Sheikh Zayed City, Giza Governorate, Egypt',
                'map_url' => 'https://maps.google.com/?q=30.0488,30.9936',
                'short_description_ar' => 'إحدى المدن الجديدة في محافظة الجيزة، تتميز بالرقي والهدوء والمساحات الخضراء الواسعة، وتعد من أهم وجهات السكن الفاخر والاستثمار العقاري في غرب القاهرة.',
                'short_description_en' => 'An upscale new city in Giza Governorate known for its tranquility, green spaces, and luxury housing, making it a top destination for real estate investment in West Cairo.',
                'about_ar' => 'مدينة الشيخ زايد هي واحدة من أبرز المدن الجديدة في مصر، وتقع في محافظة الجيزة غرب القاهرة. تمتاز بالتخطيط العمراني المتطور والبيئة الهادئة التي توفر الخصوصية والرفاهية لساكنيها. تحتوي المدينة على العديد من الكمبوندات السكنية الفاخرة مثل بيفرلي هيلز وزايد ديونز، وتضم مراكز تجارية وترفيهية كبرى مثل مول العرب وأركان بلازا ومول مصر. الطلب العقاري فيها مرتفع جداً بسبب جودة الحياة وتوفر المدارس الدولية والمستشفيات المتخصصة، مما يجعلها خياراً مثالياً للسكن العائلي الراقي.',
                'about_en' => 'Sheikh Zayed City is one of the most prominent new cities in Egypt, located in the Giza Governorate west of Cairo. It is renowned for its advanced urban planning, peaceful environment, and high level of privacy and luxury. The city hosts numerous prestigious residential compounds such as Beverly Hills and Zayed Dunes, alongside major commercial and entertainment hubs like Mall of Arabia and Arkan Plaza. Real estate demand is exceptionally high due to the quality of life, international schools, and specialized hospitals, making it an ideal choice for upscale family living.',
            ],
            [
                'name_ar' => 'الساحل الشمالي',
                'name_en' => 'North Coast',
                'slug' => 'north-coast',
                'sort_order' => 2,
                'latitude' => '30.8252',
                'longitude' => '28.9535',
                'address_ar' => 'الساحل الشمالي، طريق الإسكندرية مطروح، مصر',
                'address_en' => 'North Coast, Alexandria - Matrouh Road, Egypt',
                'map_url' => 'https://maps.google.com/?q=30.8252,28.9535',
                'short_description_ar' => 'الوجهة الساحلية الأولى في مصر على البحر الأبيض المتوسط، تمتد من الإسكندرية لمرسى مطروح وتضم أفخم القرى السياحية.',
                'short_description_en' => 'Egypt\'s premier coastal destination on the Mediterranean, stretching from Alexandria to Marsa Matruh and featuring the most luxurious tourist villages.',
                'about_ar' => 'الساحل الشمالي في مصر (ويعرف محلياً بالساحل) هو الشريط الممتد على البحر الأبيض المتوسط من غرب الإسكندرية وحتى مرسى مطروح. يُعتبر الوجهة الصيفية الأولى للمصريين والسياح الأجانب بفضل شواطئه الرملية البيضاء ومياهه الفيروزية الصافية. يشهد الساحل الشمالي طفرة هائلة في الاستثمار العقاري السياحي، حيث يضم مجموعة من أرقى وأفخم المنتجعات والقرى السياحية مثل مراسي، هاسيندا، وأمواج. بالإضافة إلى ذلك، تدعم شبكة الطرق الجديدة مثل طريق الفوكا الجديد سهولة وسرعة الوصول إليه من القاهرة، مما زاد من الإقبال على شراء الشاليهات والفلل الصيفية.',
                'about_en' => 'The North Coast (Sahel) is the premier summer destination in Egypt, stretching along the Mediterranean Sea from west of Alexandria to Marsa Matruh. It is celebrated for its pristine white sandy beaches and crystal-clear turquoise waters. The region is experiencing a massive boom in tourism real estate investment, hosting some of the most luxurious resorts and villages like Marassi, Hacienda, and Amwaj. The introduction of new infrastructure, such as the Fouka Road, has significantly shortened the travel time from Cairo, driving immense demand for chalets and summer villas.',
            ],
            [
                'name_ar' => 'الرحاب',
                'name_en' => 'Al Rehab City',
                'slug' => 'rehab',
                'sort_order' => 3,
                'latitude' => '30.0626',
                'longitude' => '31.4913',
                'address_ar' => 'مدينة الرحاب، القاهرة الجديدة، محافظة القاهرة، مصر',
                'address_en' => 'Al Rehab City, New Cairo, Cairo Governorate, Egypt',
                'map_url' => 'https://maps.google.com/?q=30.0626,31.4913',
                'short_description_ar' => 'أول مدينة سكنية متكاملة يطورها القطاع الخاص في مصر، تقع في القاهرة الجديدة وتوفر كافة الخدمات التي تحتاجها العائلة.',
                'short_description_en' => 'The first fully integrated residential city developed by the private sector in Egypt, located in New Cairo and offering comprehensive family services.',
                'about_ar' => 'مدينة الرحاب هي مشروع سكني ضخم يقع في قلب القاهرة الجديدة، وتعد أول مدينة سكنية متكاملة يبنيها القطاع الخاص في مصر (مجموعة طلعت مصطفى). تتميز الرحاب بمستوى عالي من الأمان والتنظيم والمساحات الخضراء الشاسعة. تنقسم المدينة إلى عدة مراحل تقدم مزيجاً متنوعاً من الشقق السكنية والفيلات المصممة بأساليب معمارية مختلفة. تكتفي المدينة ذاتياً بفضل توفر النوادي الرياضية، المدارس، المراكز الطبية، والسوق التجاري المفتوح، مما يجعلها بيئة سكنية مثالية وهادئة تجذب العائلات والمستثمرين للبحث عن وحدات للإيجار أو التمليك.',
                'about_en' => 'Al Rehab City is a massive residential project located in the heart of New Cairo. Developed by the Talaat Moustafa Group, it holds the title of being the first fully integrated residential city built by the private sector in Egypt. The city is highly regarded for its exceptional security, organization, and expansive green landscapes. Divided into several phases, it offers a diverse mix of apartments and villas with various architectural styles. Completely self-sufficient, Al Rehab features sports clubs, schools, medical centers, and a bustling open-air market, making it an ideal, tranquil residential environment for families and a prime spot for rental or ownership investments.',
            ],
            [
                'name_ar' => 'التجمع الخامس',
                'name_en' => 'New Cairo',
                'slug' => 'new-cairo',
                'sort_order' => 4,
                'latitude' => '30.0263',
                'longitude' => '31.4906',
                'address_ar' => 'التجمع الخامس، القاهرة الجديدة، محافظة القاهرة، مصر',
                'address_en' => 'New Cairo, Cairo Governorate, Egypt',
                'map_url' => 'https://maps.google.com/?q=30.0263,31.4906',
                'short_description_ar' => 'من أهم المدن الجديدة في مصر، تقع شرق الطريق الدائري، وتضم أرقى الأحياء السكنية والجامعات الدولية ومقار الشركات.',
                'short_description_en' => 'One of the most important new cities in Egypt, located east of the Ring Road, housing prestigious residential neighborhoods, international universities, and corporate headquarters.',
                'about_ar' => 'القاهرة الجديدة (وبالأخص التجمع الخامس) تعتبر حالياً القلب النابض للاستثمار العقاري الفاخر في شرق القاهرة. تتميز بشوارعها الواسعة مثل شارع التسعين الذي يضم كبرى البنوك والشركات والمولات التجارية (مثل كايرو فيستيفال سيتي وداون تاون). توفر القاهرة الجديدة تنوعاً عقارياً كبيراً بدءاً من الشقق السكنية في الأحياء المنظمة وصولاً إلى القصور والفيلات داخل الكمبوندات الخاصة المغلقة. كما تحتضن مؤسسات تعليمية مرموقة مثل الجامعة الأمريكية بالقاهرة (AUC) والجامعة الألمانية، مما يجعلها وجهة سكنية من الدرجة الأولى للنخبة وللباحثين عن الرفاهية.',
                'about_en' => 'New Cairo (particularly known for the Fifth Settlement / Tagamoa El Khames) is currently the beating heart of luxury real estate investment in East Cairo. It is characterized by wide avenues, most notably Road 90, which is lined with major banks, corporate headquarters, and upscale shopping malls like Cairo Festival City and Downtown. New Cairo offers a vast real estate diversity, ranging from standard apartments in organized neighborhoods to opulent palaces and villas within private gated communities. Hosting prestigious educational institutions such as the American University in Cairo (AUC) and the German University, it stands as a premier residential destination for elites and those seeking an affluent lifestyle.',
            ],
            [
                'name_ar' => 'الإسكندرية',
                'name_en' => 'Alexandria',
                'slug' => 'alexandria',
                'sort_order' => 5,
                'latitude' => '31.2001',
                'longitude' => '29.9187',
                'address_ar' => 'محافظة الإسكندرية، مصر',
                'address_en' => 'Alexandria Governorate, Egypt',
                'map_url' => 'https://maps.google.com/?q=31.2001,29.9187',
                'short_description_ar' => 'ثاني أكبر مدن مصر وعروس البحر المتوسط، تتمتع بموقع استراتيجي وتاريخ عريق وتعتبر وجهة سكنية وسياحية مميزة.',
                'short_description_en' => 'The second-largest city in Egypt and the Pearl of the Mediterranean, enjoying a strategic location, rich history, and serving as a prominent residential and tourist destination.',
                'about_ar' => 'مدينة الإسكندرية هي العاصمة الثانية لمصر وتعتبر مركزاً اقتصادياً وتجارياً حيوياً على ساحل البحر الأبيض المتوسط. تمتلك طابعاً معمارياً يجمع بين التراث العريق والحداثة، وتضم أحياء راقية للاستثمار العقاري مثل سموحة، رشدي، وكفر عبده، بالإضافة إلى المناطق الساحلية المميزة كالمندرة وسيدي بشر. لا تقتصر أهمية الإسكندرية على كونها مصيفاً تاريخياً للمصريين، بل هي مدينة متكاملة تنبض بالحياة طوال العام وتوفر فرصاً عقارية رائعة سواء للإقامة الدائمة أو للاستثمار الصيفي والتجاري.',
                'about_en' => 'Alexandria, Egypt\'s second capital, is a vital economic and commercial hub situated on the Mediterranean coast. Its architectural character beautifully blends ancient heritage with modernity. The city boasts upscale neighborhoods prime for real estate investment, such as Smouha, Roushdy, and Kafr Abdou, alongside vibrant coastal areas like El Mandara and Sidi Bishr. Beyond its legacy as a historic summer resort for Egyptians, Alexandria is a fully integrated, year-round bustling city. It offers excellent real estate opportunities for both permanent residency and summer or commercial investments.',
            ],
            [
                'name_ar' => '6 أكتوبر',
                'name_en' => '6th of October City',
                'slug' => '6th-october',
                'sort_order' => 6,
                'latitude' => '29.9714',
                'longitude' => '30.9332',
                'address_ar' => 'مدينة 6 أكتوبر، محافظة الجيزة، مصر',
                'address_en' => '6th of October City, Giza Governorate, Egypt',
                'map_url' => 'https://maps.google.com/?q=29.9714,30.9332',
                'short_description_ar' => 'مدينة سكنية وصناعية كبرى توفر خيارات عقارية تناسب كافة الفئات، وتضم جامعات ومستشفيات كبرى.',
                'short_description_en' => 'A major residential and industrial city offering real estate options for all segments, featuring major universities and hospitals.',
                'about_ar' => 'مدينة السادس من أكتوبر هي إحدى أنجح المدن الجديدة في محافظة الجيزة. تُعد مركزاً سكنياً وصناعياً مهماً، وتتميز بتقديم خيارات عقارية شديدة التنوع لتناسب كافة الشرائح، من الإسكان الاقتصادي والمتوسط إلى الكمبوندات الفاخرة والفيلات. تضم المدينة عدداً كبيراً من الجامعات الخاصة والمعاهد التعليمية والمستشفيات، إلى جانب المناطق الترفيهية والتجارية مثل مول العرب. هذا التكامل في الخدمات جعل منها بيئة خصبة للاستثمار العقاري وسوقاً نشطاً للإيجارات بفضل التوافد المستمر للطلاب والموظفين.',
                'about_en' => 'The 6th of October City is one of the most successful new cities in the Giza Governorate. Serving as an essential residential and industrial hub, it offers highly diverse real estate options that cater to all societal segments, from affordable and middle-income housing to luxury compounds and villas. The city is home to numerous private universities, educational institutes, and hospitals, as well as major entertainment and commercial centers like Mall of Arabia. This integration of services has transformed it into a fertile ground for real estate investment and a highly active rental market due to the continuous influx of students and professionals.',
            ],
            [
                'name_ar' => 'رأس الحكمة',
                'name_en' => 'Ras El Hekma',
                'slug' => 'ras-el-hekma',
                'sort_order' => 7,
                'latitude' => '31.1469',
                'longitude' => '27.8483',
                'address_ar' => 'رأس الحكمة، محافظة مطروح، مصر',
                'address_en' => 'Ras El Hekma, Matrouh Governorate, Egypt',
                'map_url' => 'https://maps.google.com/?q=31.1469,27.8483',
                'short_description_ar' => 'منطقة ساحلية واعدة على الساحل الشمالي الغربي، تشهد أضخم المشروعات التنموية والسياحية في مصر.',
                'short_description_en' => 'A highly promising coastal area on the northwestern coast, witnessing some of the most massive developmental and tourism projects in Egypt.',
                'about_ar' => 'تعد منطقة رأس الحكمة الجوهرة الجديدة للساحل الشمالي المصري، وتقع في محافظة مطروح. تحظى باهتمام استثماري هائل محلياً وعالمياً، بفضل الشواطئ الرملية الممتدة والمياه النقية التي تضاهي أرقى الوجهات العالمية. تم إطلاق مشروعات قومية واستثمارات بمليارات الدولارات لتحويل رأس الحكمة إلى مدينة سياحية عالمية تعمل طوال العام وليس فقط في فصل الصيف. تضم المنطقة حالياً والمستقبل القريب أرقى وأفخم المنتجعات الساحلية والفلل الفارهة، وتعتبر الفرصة الذهبية للمستثمرين في قطاع العقارات السياحية.',
                'about_en' => 'Ras El Hekma is the new crown jewel of the Egyptian North Coast, located in Matrouh Governorate. It commands immense local and global investment interest, thanks to its extensive sandy beaches and pristine waters that rival top international destinations. Multi-billion dollar national projects and foreign investments have been launched to transform Ras El Hekma into a world-class, year-round tourist city. Currently and in the near future, the area will host the most opulent coastal resorts and ultra-luxury villas, presenting a golden opportunity for investors in the tourism real estate sector.',
            ],
            [
                'name_ar' => 'المهندسين',
                'name_en' => 'Mohandessin',
                'slug' => 'mohandessin',
                'sort_order' => 8,
                'latitude' => '30.0526',
                'longitude' => '31.1989',
                'address_ar' => 'حي المهندسين، محافظة الجيزة، مصر',
                'address_en' => 'Mohandessin, Giza Governorate, Egypt',
                'map_url' => 'https://maps.google.com/?q=30.0526,31.1989',
                'short_description_ar' => 'من أرقى الأحياء التجارية والسكنية في قلب الجيزة، يشتهر بشوارعه الواسعة وتوفر كافة الخدمات ومقار الشركات.',
                'short_description_en' => 'One of the most prestigious commercial and residential districts in the heart of Giza, famous for its wide streets and abundance of services and corporate offices.',
                'about_ar' => 'تأسس حي المهندسين في أوائل الخمسينيات، ويُعد اليوم واحداً من أهم المناطق الحيوية والراقية في محافظة الجيزة والقاهرة الكبرى. يمزج الحي بشكل فريد بين الطابع السكني الراقي والنشاط التجاري المكثف. يتميز بميادينه وشوارعه الرئيسية المعروفة مثل شارع جامعة الدول العربية وشارع البطل أحمد عبد العزيز وشارع شهاب، والتي تكتظ بالمطاعم الفاخرة، العلامات التجارية العالمية، ومقرات الشركات الكبرى. العقارات في المهندسين تحظى بقيمة عالية جداً، سواء للراغبين في السكن بقلب المدينة أو الباحثين عن مساحات إدارية وتجارية متميزة.',
                'about_en' => 'Established in the early 1950s, Mohandessin is today one of the most vital and upscale districts in Giza Governorate and Greater Cairo. The neighborhood uniquely blends high-end residential living with intense commercial activity. It is renowned for its major squares and iconic streets, such as Gamal Abdel Nasser (Arab League) Street, Batal Ahmed Abdel Aziz Street, and Shehab Street, which are bustling with fine dining restaurants, global retail brands, and major corporate headquarters. Real estate in Mohandessin holds exceptionally high value, whether for those seeking to live in the city center or businesses looking for prime administrative and commercial spaces.',
            ],
            [
                'name_ar' => 'المعادي',
                'name_en' => 'Maadi',
                'slug' => 'maadi',
                'sort_order' => 9,
                'latitude' => '29.9602',
                'longitude' => '31.2569',
                'address_ar' => 'المعادي، محافظة القاهرة، مصر',
                'address_en' => 'Maadi, Cairo Governorate, Egypt',
                'map_url' => 'https://maps.google.com/?q=29.9602,31.2569',
                'short_description_ar' => 'ضاحية عريقة في جنوب القاهرة، تشتهر بالهدوء والأشجار والفيلات الكلاسيكية، وتعتبر وجهة مفضلة للدبلوماسيين والجاليات الأجنبية.',
                'short_description_en' => 'A historic suburb in southern Cairo, famous for its tranquility, trees, and classic villas, a favorite destination for diplomats and foreign communities.',
                'about_ar' => 'المعادي هي إحدى أرقى وأهدأ ضواحي محافظة القاهرة، تتميز بتخطيطها الفريد الذي يعتمد على الميادين والشوارع المشجرة والفيلات ذات الطراز المعماري الكلاسيكي. تنقسم المعادي إلى عدة مناطق رئيسية مثل المعادي القديمة، ثكنات المعادي، زهراء المعادي، ودجلة. بفضل مستوى الأمان المرتفع وتواجد العديد من المدارس الدولية والمراكز الثقافية، تُعد المعادي المقر المفضل لسكن السفراء، الدبلوماسيين، والجاليات الأجنبية في مصر. سوق العقارات في المعادي يحافظ دائماً على استقراره وقيمته الاستثمارية العالية خصوصاً في الفيلات والشقق السكنية الراقية.',
                'about_en' => 'Maadi is one of the most affluent and serene suburbs in Cairo Governorate, characterized by its unique layout centered around leafy squares, tree-lined streets, and classically designed villas. Maadi is divided into several main areas, including Old Maadi, Maadi Sarayat, Zahraa El Maadi, and Degla. Due to its high level of security and the presence of numerous international schools and cultural centers, Maadi is the preferred residential hub for ambassadors, diplomats, and expatriate communities in Egypt. The real estate market in Maadi consistently maintains its stability and high investment value, particularly in the premium villa and luxury apartment segments.',
            ],
            [
                'name_ar' => 'العين السخنة',
                'name_en' => 'Ain Sokhna',
                'slug' => 'ain-sokhna',
                'sort_order' => 10,
                'latitude' => '29.5933',
                'longitude' => '32.3275',
                'address_ar' => 'العين السخنة، محافظة السويس، مصر',
                'address_en' => 'Ain Sokhna, Suez Governorate, Egypt',
                'map_url' => 'https://maps.google.com/?q=29.5933,32.3275',
                'short_description_ar' => 'أقرب منتجع ساحلي للقاهرة على خليج السويس، توفر خيارات استثمارية وسياحية مميزة طوال العام بفضل مناخها المعتدل.',
                'short_description_en' => 'The closest coastal resort to Cairo on the Gulf of Suez, offering excellent year-round investment and tourism options due to its temperate climate.',
                'about_ar' => 'العين السخنة هي إحدى أهم الوجهات السياحية والاستثمارية على ساحل خليج السويس، وتتبع إدارياً محافظة السويس. ميزتها التنافسية الأكبر هي قربها الشديد من القاهرة، حيث يمكن الوصول إليها في نحو ساعة عبر طريق الجلالة السريع، مما جعلها وجهة "عطلات نهاية الأسبوع" المفضلة للمصريين على مدار السنة وليس فقط في الصيف. شهدت المنطقة قفزة تنموية وعقارية غير مسبوقة بفضل المشروعات القومية مثل مدينة الجلالة الجديدة ومنتجع المونت جلالة وتلال، حيث يزخر السوق بوحدات سكنية وفندقية راقية تطل مباشرة على البحر الأحمر.',
                'about_en' => 'Ain Sokhna is a paramount tourist and investment destination on the coast of the Gulf of Suez, administratively part of the Suez Governorate. Its biggest competitive advantage is its extreme proximity to Cairo—reachable in about an hour via the Galala Highway. This accessibility has made it the preferred year-round "weekend getaway" for Egyptians, rather than just a summer retreat. The area has experienced an unprecedented developmental and real estate leap thanks to national mega-projects like the New Galala City, Il Monte Galala, and Telal. The market is abundant with high-end residential and hotel units offering direct views of the Red Sea.',
            ],
            [
                'name_ar' => 'العجمي',
                'name_en' => 'Agami',
                'slug' => 'agami',
                'sort_order' => 11,
                'latitude' => '31.1118',
                'longitude' => '29.7619',
                'address_ar' => 'العجمي، الإسكندرية، مصر',
                'address_en' => 'Agami, Alexandria, Egypt',
                'map_url' => 'https://maps.google.com/?q=31.1118,29.7619',
                'short_description_ar' => 'حي ساحلي شهير في غرب الإسكندرية، يُعتبر المصيف الكلاسيكي للمصريين ويضم مناطق حيوية وتجارية نشطة.',
                'short_description_en' => 'A famous coastal district in western Alexandria, considered the classic summer resort for Egyptians, featuring active commercial areas.',
                'about_ar' => 'العجمي هو واحد من أعرق أحياء الإسكندرية ويقع في الجزء الغربي من المحافظة. ارتبط اسمه لفترة طويلة بكونه المصيف المفضل للطبقة الراقية والمثقفين في مصر خلال القرن الماضي. يضم العجمي مناطق شهيرة مثل البيطاش، الهانوفيل، أبو يوسف، وسيدي كرير. حالياً، تحول العجمي من مجرد مصيف إلى منطقة سكنية وتجارية مكتظة تعمل طوال العام. يتنوع السوق العقاري في العجمي بشكل كبير، حيث تجد الشقق السكنية الاقتصادية والمتوسطة إلى جانب القرى السياحية المغلقة التي توفر شاليهات وفيلات لمحبي قضاء العطلات الصيفية.',
                'about_en' => 'Agami is one of the most historic districts in Alexandria, located in the western part of the governorate. For a long time, it was renowned as the preferred summer retreat for Egypt\'s elite and intellectuals during the last century. Agami encompasses famous neighborhoods like El Bitash, El Hanouvile, Abu Youssef, and Sidi Krier. Today, Agami has transitioned from a mere summer resort into a densely populated, year-round residential and commercial area. The real estate market in Agami is highly diverse, offering everything from affordable and mid-range apartments to gated tourist villages providing chalets and villas for vacationers.',
            ],
            [
                'name_ar' => 'العاصمة الإدارية',
                'name_en' => 'New Administrative Capital',
                'slug' => 'new-administrative-capital',
                'sort_order' => 12,
                'latitude' => '29.9820',
                'longitude' => '31.7208',
                'address_ar' => 'العاصمة الإدارية الجديدة، محافظة القاهرة، مصر',
                'address_en' => 'New Administrative Capital, Cairo Governorate, Egypt',
                'map_url' => 'https://maps.google.com/?q=29.9820,31.7208',
                'short_description_ar' => 'المشروع القومي الأضخم في مصر، صُممت لتكون مدينة ذكية عالمية ومركزاً مالياً وإدارياً حديثاً يوفر أحدث المشروعات العقارية.',
                'short_description_en' => 'Egypt\'s most massive national project, designed as a world-class smart city and a modern financial and administrative hub offering cutting-edge real estate.',
                'about_ar' => 'العاصمة الإدارية الجديدة هي المشروع القومي الأضخم والأهم في تاريخ مصر الحديث. تقع شرق القاهرة وتهدف إلى تخفيف الازدحام عن العاصمة القديمة وتأسيس مدينة ذكية مستدامة تواكب أحدث المعايير العالمية. تضم العاصمة مقرات الوزارات، البنك المركزي، حي المال والأعمال، وأيقونات معمارية مبهرة مثل البرج الأيقوني (الأطول في أفريقيا) والنهر الأخضر. تمثل العاصمة الإدارية بؤرة الاستثمار العقاري الأولى في الشرق الأوسط حالياً، حيث توفر فرصاً استثنائية لشراء العقارات الإدارية، التجارية، والشقق والفيلات السكنية المتطورة داخل كمبوندات توفر أعلى مستويات الرفاهية.',
                'about_en' => 'The New Administrative Capital is the largest and most significant national project in modern Egyptian history. Located east of Cairo, it aims to alleviate congestion in the old capital by establishing a sustainable smart city built to the latest global standards. The capital houses government ministries, the Central Bank, the Central Business District (CBD), and stunning architectural icons like the Iconic Tower (the tallest in Africa) and the Green River. It currently represents the epicenter of real estate investment in the Middle East, offering exceptional opportunities to purchase advanced administrative, commercial, and residential properties within compounds that guarantee the highest levels of luxury.',
            ],
            [
                'name_ar' => 'سيدي عبد الرحمن',
                'name_en' => 'Sidi Abdel Rahman',
                'slug' => 'sidi-abdel-rahman',
                'sort_order' => 13,
                'latitude' => '30.9634',
                'longitude' => '28.7188',
                'address_ar' => 'سيدي عبد الرحمن، العلمين، محافظة مطروح، مصر',
                'address_en' => 'Sidi Abdel Rahman, El Alamein, Matrouh Governorate, Egypt',
                'map_url' => 'https://maps.google.com/?q=30.9634,28.7188',
                'short_description_ar' => 'من أجمل مناطق الساحل الشمالي، تتميز بشواطئها ذات الرمال البيضاء الناصعة وتضم أشهر المشروعات العقارية الفاخرة.',
                'short_description_en' => 'One of the most beautiful areas in the North Coast, featuring pristine white sandy beaches and housing the most renowned luxury real estate projects.',
                'about_ar' => 'سيدي عبد الرحمن هي منطقة ساحلية خلابة تتبع مركز العلمين بمحافظة مطروح، وتعتبر من أهم وأغلى مناطق الساحل الشمالي المصري. اكتسبت شهرتها الواسعة بسبب لون مياهها الفيروزي النادر ورمالها البيضاء الناعمة، وهو ما جذب كبار المطورين العقاريين لإنشاء أضخم وأفخم القرى السياحية هناك، لعل أشهرها منتجع "مراسي". العقارات في سيدي عبد الرحمن تعتبر من العقارات الفاخرة ذات العائد الاستثماري المرتفع جداً، وتستقطب الباحثين عن مستوى حياة صيفي حصري ومميز يتضمن ملاعب الجولف، المرسى الدولي لليخوت، والفنادق العالمية.',
                'about_en' => 'Sidi Abdel Rahman is a breathtaking coastal area affiliated with the El Alamein center in Matrouh Governorate, and is considered one of the most important and expensive areas of the Egyptian North Coast. It gained widespread fame due to its rare turquoise water and soft white sand, which attracted top-tier real estate developers to build the largest and most luxurious tourist villages there, most notably the "Marassi" resort. Real estate in Sidi Abdel Rahman is highly luxurious with an exceptionally high ROI, attracting those seeking an exclusive summer lifestyle that includes golf courses, an international yacht marina, and world-class hotels.',
            ],
            [
                'name_ar' => 'مدينة نصر',
                'name_en' => 'Nasr City',
                'slug' => 'nasr-city',
                'sort_order' => 14,
                'latitude' => '30.0638',
                'longitude' => '31.3283',
                'address_ar' => 'مدينة نصر، محافظة القاهرة، مصر',
                'address_en' => 'Nasr City, Cairo Governorate, Egypt',
                'map_url' => 'https://maps.google.com/?q=30.0638,31.3283',
                'short_description_ar' => 'أحد أكبر أحياء العاصمة، مركز حيوي للتجارة والأعمال يتميز بالتخطيط المنظم وتوفر خيارات سكنية وتجارية واسعة.',
                'short_description_en' => 'One of the capital\'s largest districts, a vital hub for commerce and business featuring organized planning and extensive residential and commercial options.',
                'about_ar' => 'مدينة نصر هي أحد أكبر أحياء القاهرة وأكثرها كثافة سكانية وحيوية، وقد تأسست في الستينيات كامتداد معماري حديث للعاصمة. تُعد مدينة نصر عصب التجارة والأعمال في المنطقة الشرقية، وتتميز بشوارعها الواسعة والمتقاطعة بشكل هندسي منظم مثل شارع مكرم عبيد، عباس العقاد، ومصطفى النحاس. توفر المنطقة كافة أنواع الخدمات وتضم مؤسسات حكومية هامة ومراكز تسوق ضخمة أشهرها "سيتي ستارز". القطاع العقاري في مدينة نصر متنوع جداً، ويشهد نشاطاً كبيراً في بيع وإيجار الشقق السكنية والمساحات التجارية والإدارية للشركات والعيادات.',
                'about_en' => 'Nasr City is one of Cairo\'s largest, most densely populated, and vibrant districts, established in the 1960s as a modern architectural extension to the capital. It serves as the commercial and business nerve center in the eastern region, characterized by its wide, geometrically organized intersecting streets such as Makram Ebeid, Abbas El Akkad, and Moustafa El Nahhas. The area provides all types of services and houses important government institutions and massive shopping malls, most famously "Citystars". The real estate sector in Nasr City is highly diverse, experiencing robust activity in the sale and rental of residential apartments, as well as commercial and administrative spaces for businesses and clinics.',
            ],
            [
                'name_ar' => 'مرسى مطروح',
                'name_en' => 'Marsa Matruh',
                'slug' => 'marsa-matruh',
                'sort_order' => 15,
                'latitude' => '31.3533',
                'longitude' => '27.2373',
                'address_ar' => 'مرسى مطروح، محافظة مطروح، مصر',
                'address_en' => 'Marsa Matruh, Matrouh Governorate, Egypt',
                'map_url' => 'https://maps.google.com/?q=31.3533,27.2373',
                'short_description_ar' => 'عاصمة محافظة مطروح، تشتهر بشواطئها الفريدة وتعتبر من أهم الوجهات السياحية الداخلية في مصر للباحثين عن الهدوء.',
                'short_description_en' => 'The capital of Matrouh Governorate, famous for its unique beaches and serving as one of Egypt\'s premier domestic tourism destinations for those seeking tranquility.',
                'about_ar' => 'مرسى مطروح هي الميناء البحري وعاصمة محافظة مطروح، وتتربع كواحدة من أروع الوجهات الساحلية على البحر الأبيض المتوسط. تتميز مطروح بشواطئ استثنائية ذات طبيعة بكر ومياه متدرجة الألوان وأمواج هادئة بسبب التكوينات الصخرية الطبيعية، مثل شاطئ عجيبة، روميل، والغرام. المدينة تُعد الملاذ الصيفي المفضل للآلاف من الأسر المصرية التي تبحث عن الهدوء والاستجمام بأسعار معقولة. وقد شهدت المنطقة مؤخراً طفرة في المشروعات العقارية التي توفر شاليهات وفيلات وشقق مصيفية تناسب مختلف الميزانيات، مدعومة بتطوير البنية التحتية وشبكة الطرق المؤدية إليها.',
                'about_en' => 'Marsa Matruh is the seaport and capital of Matrouh Governorate, reigning as one of the most magnificent coastal destinations on the Mediterranean. Matruh is distinguished by its exceptional beaches with pristine nature, gradient waters, and calm waves protected by natural rock formations, such as Ageeba, Rommel, and El Gharam beaches. The city is the favored summer retreat for thousands of Egyptian families seeking tranquility and relaxation at affordable prices. Recently, the region has seen a surge in real estate projects offering chalets, villas, and summer apartments that fit various budgets, bolstered by infrastructure development and improved access road networks.',
            ],
            [
                'name_ar' => 'مصر الجديدة',
                'name_en' => 'Heliopolis',
                'slug' => 'heliopolis',
                'sort_order' => 16,
                'latitude' => '30.0911',
                'longitude' => '31.3236',
                'address_ar' => 'حي مصر الجديدة، محافظة القاهرة، مصر',
                'address_en' => 'Heliopolis, Cairo Governorate, Egypt',
                'map_url' => 'https://maps.google.com/?q=30.0911,31.3236',
                'short_description_ar' => 'من أرقى وأعرق أحياء القاهرة، يتميز بطرازه المعماري الفريد ومعالمه الشهيرة، ويوفر بيئة سكنية فاخرة وراقية.',
                'short_description_en' => 'One of Cairo\'s most prestigious and historic districts, distinguished by its unique architectural style and famous landmarks, providing a luxurious residential environment.',
                'about_ar' => 'حي مصر الجديدة (هيليوبوليس) هو تحفة معمارية وتاريخية وأحد أرقى أحياء العاصمة المصرية. أسسه المهندس ورجل الأعمال البلجيكي البارون إمبان في أوائل القرن العشرين ليكون مدينة "كوزموبوليتانية" تدمج بين التراث الإسلامي والعمارة الأوروبية الحديثة. يتميز الحي بالشوارع والميادين الكبيرة، والقصور التاريخية مثل "قصر البارون"، والمناطق التجارية الراقية مثل "الكوربة". تحتفظ عقارات مصر الجديدة بقيمتها التراثية والمادية العالية جداً، وتجذب العائلات الأرستقراطية ورجال الأعمال الباحثين عن مستوى اجتماعي راقٍ، سواء للسكن في فيلات وشقق فخمة أو لافتتاح مقار لشركات وعلامات تجارية كبرى.',
                'about_en' => 'Heliopolis (Masr El Gedida) is an architectural and historical masterpiece and one of the most upscale districts in the Egyptian capital. Founded in the early 20th century by the Belgian industrialist Baron Empain, it was designed as a "cosmopolitan" city blending Islamic heritage with modern European architecture. The district is characterized by its large streets and squares, historic palaces like the "Baron Empain Palace," and sophisticated commercial areas such as "El Korba." Real estate in Heliopolis retains extremely high heritage and monetary value, attracting aristocratic families and business figures seeking a prestigious social standing, whether for residing in luxury villas and apartments or opening headquarters for major corporate brands.',
            ]
        ];
