export const PLACEHOLDER = 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 600"%3E%3Crect fill="%23F0F0F0" width="800" height="600"/%3E%3C/svg%3E'

/**
 * Normalizes an image path to ensure proper /storage/ URL format without duplicate storage/storage prefixes.
 */
export function getStorageUrl(path, fallback = PLACEHOLDER) {
    if (!path || typeof path !== 'string') {
        return fallback
    }

    const trimmed = path.trim()
    if (!trimmed) {
        return fallback
    }

    // Direct HTTP/HTTPS or SVG data URLs
    if (trimmed.startsWith('http://') || trimmed.startsWith('https://') || trimmed.startsWith('data:')) {
        return trimmed
    }

    // Strip any leading slashes or duplicate storage prefixes
    let clean = trimmed.replace(/^\/+/, '')
    if (clean.startsWith('storage/')) {
        clean = clean.replace(/^storage\/+/, '')
    }

    return `/storage/${clean}`
}

/**
 * Returns the corresponding thumbnail path if it was generated by the backend
 */
export function getThumbUrl(path, fallback = PLACEHOLDER) {
    if (!path || typeof path !== 'string') {
        return fallback
    }

    const trimmed = path.trim()
    if (!trimmed || trimmed.startsWith('http://') || trimmed.startsWith('https://') || trimmed.startsWith('data:')) {
        return getStorageUrl(path, fallback)
    }

    let clean = trimmed.replace(/^\/+/, '')
    if (clean.startsWith('storage/')) {
        clean = clean.replace(/^storage\/+/, '')
    }

    // Backend generates thumbnails like: path/to/thumb_filename.webp
    const parts = clean.split('/')
    const filename = parts.pop()
    
    if (filename.startsWith('thumb_')) {
        return getStorageUrl(path, fallback)
    }
    
    const nameWithoutExt = filename.substring(0, filename.lastIndexOf('.')) || filename
    const newFilename = `thumb_${nameWithoutExt}.webp`
    
    if (parts.length > 0) {
        return `/storage/${parts.join('/')}/${newFilename}`
    }
    return `/storage/${newFilename}`
}

/**
 * Compresses and scales an image file on the client side using HTML5 Canvas
 * to dramatically reduce upload size (e.g. from 15MB to ~200KB) and speed up uploads.
 *
 * @param {File} file - The raw image File object from input / drop event
 * @param {Object} options
 * @param {number} [options.maxWidth=1920] - Max width in pixels
 * @param {number} [options.maxHeight=1920] - Max height in pixels
 * @param {number} [options.quality=0.85] - WebP / JPEG output quality (0 to 1)
 * @returns {Promise<File>} Compressed File or original file if compression is not needed / supported
 */
export async function compressImage(file, { maxWidth = 2048, maxHeight = 2048, quality = 0.88 } = {}) {
    if (!file || !(file instanceof File) || !file.type || !file.type.startsWith('image/')) {
        return file;
    }

    // Skip SVGs and animated GIFs
    if (file.type === 'image/svg+xml' || file.type === 'image/gif') {
        return file;
    }

    return new Promise((resolve) => {
        const img = new Image();
        const objectUrl = URL.createObjectURL(file);

        img.onload = () => {
            URL.revokeObjectURL(objectUrl);

            let { width, height } = img;

            // If image is already smaller than maxWidth/maxHeight and smaller than 400KB, return original
            if (width <= maxWidth && height <= maxHeight && file.size <= 400 * 1024) {
                resolve(file);
                return;
            }

            // Calculate proportional dimensions
            if (width > maxWidth || height > maxHeight) {
                if (width / height > maxWidth / maxHeight) {
                    height = Math.round((height * maxWidth) / width);
                    width = maxWidth;
                } else {
                    width = Math.round((width * maxHeight) / height);
                    height = maxHeight;
                }
            }

            const canvas = document.createElement('canvas');
            canvas.width = width;
            canvas.height = height;

            const ctx = canvas.getContext('2d');
            if (!ctx) {
                resolve(file);
                return;
            }

            ctx.drawImage(img, 0, 0, width, height);

            const outputType = 'image/webp';
            const originalName = file.name.replace(/\.[^/.]+$/, '');
            const newName = `${originalName}.webp`;

            canvas.toBlob(
                (blob) => {
                    if (!blob) {
                        resolve(file);
                        return;
                    }

                    if (blob.size >= file.size) {
                        resolve(file);
                        return;
                    }

                    const compressedFile = new File([blob], newName, {
                        type: outputType,
                        lastModified: Date.now(),
                    });

                    resolve(compressedFile);
                },
                outputType,
                quality
            );
        };

        img.onerror = () => {
            URL.revokeObjectURL(objectUrl);
            resolve(file);
        };

        img.src = objectUrl;
    });
}
