import { spawn, execSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import http from 'node:http'

const PRERENDER_DIR = path.join(process.cwd(), 'storage', 'app', 'prerendered')
const STAGING_DIR = path.join(process.cwd(), 'storage', 'app', 'prerendered.new')
const BACKUP_DIR = path.join(process.cwd(), 'storage', 'app', 'prerendered.old')
const BUILD_DIR = path.join(process.cwd(), 'public', 'build')
const MANIFEST_PATH = path.join(BUILD_DIR, 'manifest.json')
const SSR_PORT = 13714
const ALLOW_FAILURES = process.env.PRERENDER_ALLOW_FAILURES === '1'

async function main() {
    console.log('[Prerender] Starting static HTML prerendering...')

    const ssrBundlePath = path.join(process.cwd(), 'bootstrap', 'ssr', 'ssr.js')
    if (!fs.existsSync(ssrBundlePath)) {
        console.error('[Prerender] Error: SSR bundle not found at bootstrap/ssr/ssr.js. Run "vite build --ssr" first.')
        process.exit(1)
    }

    if (!fs.existsSync(MANIFEST_PATH)) {
        console.error('[Prerender] Error: Vite build manifest not found at public/build/manifest.json. Run "vite build" first.')
        process.exit(1)
    }

    // Launch SSR server
    console.log('[Prerender] Spawning SSR server process...')
    const ssrProcess = spawn('node', [ssrBundlePath], {
        stdio: 'inherit',
        shell: true,
        env: { ...process.env, PORT: SSR_PORT },
    })

    // Wait until SSR server is actively accepting connections
    const serverReady = await waitForServer(SSR_PORT, 15000)
    if (!serverReady) {
        console.error(`[Prerender] Error: SSR server did not start on port ${SSR_PORT} within 15 seconds.`)
        try { ssrProcess.kill('SIGTERM') } catch {}
        process.exit(1)
    }

    try {
        console.log('[Prerender] Fetching page targets and templates from Laravel...')
        execSync('php artisan prerender:data', { stdio: 'inherit' })
        const jsonPath = path.join(process.cwd(), 'storage', 'app', 'prerender_pages.json')
        if (!fs.existsSync(jsonPath)) {
            throw new Error(`File ${jsonPath} was not generated by php artisan prerender:data`)
        }
        const rawData = fs.readFileSync(jsonPath, 'utf-8')
        const pages = JSON.parse(rawData.trim())

        if (pages.length < 10) {
            throw new Error(
                `Only ${pages.length} pages were exported — expected at least 10 (2 locales x 5 core pages). ` +
                'Is the database reachable and the site healthy? Fix the cause and re-run.'
            )
        }
        console.log(`[Prerender] Found ${pages.length} pages to prerender.`)

        // Clean staging dir for an atomic swap at the end
        fs.rmSync(STAGING_DIR, { recursive: true, force: true })
        fs.mkdirSync(STAGING_DIR, { recursive: true })

        let count = 0
        const failures = []
        for (const item of pages) {
            try {
                const ssrResult = await renderPage(item.page)
                const fullHtml = mergeHtml(item.htmlTemplate, ssrResult, item.baseUrl)

                assertCleanEncoding(fullHtml, item.url)

                const targetFile = path.join(STAGING_DIR, item.output)
                fs.mkdirSync(path.dirname(targetFile), { recursive: true })
                fs.writeFileSync(targetFile, fullHtml, 'utf-8')
                count++
            } catch (err) {
                failures.push({ url: item.url, error: err.message })
                console.warn(`[Prerender] Failed to render ${item.url}:`, err.message)
            }
        }

        console.log(`[Prerender] Generated ${count}/${pages.length} static HTML pages in staging.`)

        if (failures.length > 0) {
            const summary = failures.map(({ url }) => url).join(', ')
            if (ALLOW_FAILURES) {
                console.warn(`[Prerender] ${failures.length} page(s) failed but PRERENDER_ALLOW_FAILURES=1 — keeping the successful set: ${summary}`)
            } else {
                throw new Error(`Prerendering failed for ${failures.length} page(s): ${summary}`)
            }
        }

        // Strict post-generation verification across ALL generated files
        console.log('[Prerender] Verifying all generated files for localhost leakage, stale hashes, and missing assets...')
        validateAllStagingFiles(STAGING_DIR)

        // Atomic swap
        if (fs.existsSync(BACKUP_DIR)) {
            fs.rmSync(BACKUP_DIR, { recursive: true, force: true })
        }
        if (fs.existsSync(PRERENDER_DIR)) {
            fs.renameSync(PRERENDER_DIR, BACKUP_DIR)
        }
        fs.renameSync(STAGING_DIR, PRERENDER_DIR)
        fs.rmSync(BACKUP_DIR, { recursive: true, force: true })

        console.log('[Prerender] Done — all prerendered pages verified and live.')
    } catch (err) {
        console.error('[Prerender] Error during prerender process:', err.message ?? err)
        if (fs.existsSync(STAGING_DIR)) {
            fs.rmSync(STAGING_DIR, { recursive: true, force: true })
        }
        process.exitCode = 1
    } finally {
        console.log('[Prerender] Terminating SSR server...')
        ssrProcess.kill('SIGTERM')
    }
}

async function waitForServer(port, maxWaitMs = 15000) {
    const start = Date.now()
    while (Date.now() - start < maxWaitMs) {
        const isUp = await new Promise((resolve) => {
            const req = http.request(
                {
                    hostname: '127.0.0.1',
                    port,
                    path: '/render',
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json', 'Content-Length': '2' },
                    timeout: 1000,
                },
                res => {
                    res.resume()
                    resolve(true)
                }
            )
            req.on('error', () => resolve(false))
            req.on('timeout', () => { req.destroy(); resolve(false) })
            req.write('{}')
            req.end()
        })
        if (isUp) return true
        await new Promise((r) => setTimeout(r, 400))
    }
    return false
}

function renderPage(pageObject, maxAttempts = 5) {
    return new Promise((resolve, reject) => {
        const attempt = (n) => {
            const payload = JSON.stringify(pageObject)
            const req = http.request(
                {
                    hostname: '127.0.0.1',
                    port: SSR_PORT,
                    path: '/render',
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'Content-Length': Buffer.byteLength(payload),
                    },
                },
                res => {
                    const chunks = []
                    res.on('data', chunk => chunks.push(Buffer.from(chunk)))
                    res.on('end', () => {
                        const data = Buffer.concat(chunks).toString('utf-8')

                        if (res.statusCode >= 200 && res.statusCode < 300) {
                            try {
                                const result = JSON.parse(data)
                                const rendered = `${result.body ?? ''}${(result.head ?? []).join('')}`
                                if (rendered.includes('\uFFFD') && n < maxAttempts) {
                                    console.warn(`[Prerender] Corrupted UTF-8 in SSR output for ${pageObject.url}, retrying (${n}/${maxAttempts})...`)
                                    return setTimeout(() => attempt(n + 1), 300)
                                }
                                resolve(result)
                            } catch (e) {
                                reject(e)
                            }
                        } else {
                            if (n < maxAttempts) {
                                return setTimeout(() => attempt(n + 1), 500)
                            }
                            reject(new Error(`HTTP ${res.statusCode}: ${data}`))
                        }
                    })
                }
            )

            req.on('error', (err) => {
                if (n < maxAttempts) {
                    setTimeout(() => attempt(n + 1), 500)
                } else {
                    reject(err)
                }
            })
            req.write(payload)
            req.end()
        }

        attempt(1)
    })
}

function mergeHtml(templateHtml, ssrResult, rawBaseUrl) {
    let finalHtml = templateHtml

    if (ssrResult?.body) {
        // Replace the empty #app placeholder div with the SSR-rendered body.
        finalHtml = finalHtml.replace(/<div id="app"[^>]*>\s*<\/div>/, ssrResult.body)

        if (Array.isArray(ssrResult?.head) && ssrResult.head.length > 0) {
            // Strip server-rendered placeholder tags (marked with the "inertia" attribute or JSON-LD scripts)
            // so the SSR head becomes the single source of truth — avoids duplicate title/meta/schema.
            finalHtml = finalHtml
                .replace(/<title\b[^>]*\binertia\b[^>]*>[\s\S]*?<\/title>/gi, '')
                .replace(/<(?:meta|link)\b[^>]*\binertia\b[^>]*\/?>/gi, '')
                .replace(/<script\b[^>]*\binertia\b[^>]*>[\s\S]*?<\/script>/gi, '')
                .replace(/<script\b[^>]*type=["']application\/ld\+json["'][^>]*>[\s\S]*?<\/script>/gi, '')

            const headTags = ssrResult.head.join('\n')
            finalHtml = finalHtml.replace('</head>', `${headTags}\n</head>`)
        }
    }

    // Determine clean production base URL
    let targetBaseUrl = (rawBaseUrl || '').trim()
    if (!targetBaseUrl || targetBaseUrl.includes('127.0.0.1') || targetBaseUrl.includes('localhost')) {
        targetBaseUrl = 'https://familyhome-co.com'
    }
    targetBaseUrl = targetBaseUrl.replace(/\/+$/, '')

    // 1. Strip dev host prefix from static assets and fonts/images, making them clean root-relative
    finalHtml = finalHtml
        .replace(/https?:\\\/\\\/(?:localhost|127\.0\.0\.1)(?::\d+)?(\\\/build\\\/[^\s"'>]+|\\\/images\\\/[^\s"'>]+|\\\/fonts\\\/[^\s"'>]+|\\\/storage\\\/[^\s"'>]+|\\\/(?:favicon\.ico|icon\.(?:png|webp)|site\.webmanifest))/gi, '$1')
        .replace(/https?:\/\/(?:localhost|127\.0\.0\.1)(?::\d+)?(\/build\/[^\s"'>]+|\/images\/[^\s"'>]+|\/fonts\/[^\s"'>]+|\/storage\/[^\s"'>]+|\/(?:favicon\.ico|icon\.(?:png|webp)|site\.webmanifest))/gi, '$1')

    // 2. Replace any remaining dev-host URLs in canonical, og:url, og:image, schema with clean targetBaseUrl
    const escapedBase = targetBaseUrl.replace(/\//g, '\\/')
    finalHtml = finalHtml
        .replace(/https?:\\\/\\\/(?:localhost|127\.0\.0\.1)(?::\d+)?/gi, escapedBase)
        .replace(/https?:\/\/(?:localhost|127\.0\.0\.1)(?::\d+)?/gi, targetBaseUrl)

    return finalHtml
}

function validateAllStagingFiles(dir) {
    const manifestRaw = fs.readFileSync(MANIFEST_PATH, 'utf-8')
    const manifest = JSON.parse(manifestRaw)

    const validAssetFiles = new Set()
    for (const entry of Object.values(manifest)) {
        if (entry.file) {
            validAssetFiles.add(path.basename(entry.file))
        }
        if (Array.isArray(entry.assets)) {
            for (const a of entry.assets) {
                validAssetFiles.add(path.basename(a))
            }
        }
    }

    const htmlFiles = getHtmlFilesRecursive(dir)
    if (htmlFiles.length === 0) {
        throw new Error('No HTML files were generated in staging directory.')
    }

    let localhostViolations = []
    let assetViolations = []

    for (const file of htmlFiles) {
        const relativePath = path.relative(dir, file)
        const html = fs.readFileSync(file, 'utf-8')

        // 1. Check for localhost / 127.0.0.1
        if (/127\.0\.0\.1|localhost|:8000/i.test(html)) {
            const matches = html.match(/https?:\/\/(?:127\.0\.0\.1|localhost)[^\s"'>]*/gi) || ['localhost reference']
            localhostViolations.push({ file: relativePath, matches })
        }

        // 2. Extract referenced assets
        const assetMatches = Array.from(html.matchAll(/\/assets\/([a-zA-Z0-9_\-\.]+\.(?:js|css|woff2))/gi)).map(m => m[1])
        for (const filename of assetMatches) {
            if (!validAssetFiles.has(filename)) {
                assetViolations.push({ file: relativePath, asset: filename, reason: 'Not in manifest.json' })
            } else if (!fs.existsSync(path.join(BUILD_DIR, 'assets', filename))) {
                assetViolations.push({ file: relativePath, asset: filename, reason: 'File missing from public/build/assets' })
            }
        }
    }

    if (localhostViolations.length > 0) {
        const details = localhostViolations.map(v => `${v.file}: ${v.matches.join(', ')}`).join('\n')
        throw new Error(`[Prerender Verification Failed] Localhost/127.0.0.1 found in ${localhostViolations.length} file(s):\n${details}`)
    }

    if (assetViolations.length > 0) {
        const details = assetViolations.map(v => `${v.file}: ${v.asset} (${v.reason})`).join('\n')
        throw new Error(`[Prerender Verification Failed] Stale or missing assets found in ${assetViolations.length} reference(s):\n${details}`)
    }

    console.log(`[Prerender] Verification Passed: 0 localhost links, 0 stale hashes across ${htmlFiles.length} files.`)
}

function getHtmlFilesRecursive(dir) {
    let results = []
    if (!fs.existsSync(dir)) return results
    const list = fs.readdirSync(dir)
    for (const file of list) {
        const full = path.join(dir, file)
        const stat = fs.statSync(full)
        if (stat && stat.isDirectory()) {
            results = results.concat(getHtmlFilesRecursive(full))
        } else if (file.endsWith('.html')) {
            results.push(full)
        }
    }
    return results
}

function assertCleanEncoding(html, url) {
    if (html.includes('\uFFFD')) {
        throw new Error(`Replacement character (U+FFFD) found in prerendered HTML for ${url} — encoding corruption.`)
    }
    if (/(?:[\u00C0-\u00FF]{3,})/.test(html)) {
        throw new Error(`Double-encoded (mojibake) text detected in prerendered HTML for ${url}. Aborting to avoid serving corrupted content.`)
    }
}

main()
