import { spawn, execSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import http from 'node:http'

const PRERENDER_DIR = path.join(process.cwd(), 'storage', 'app', 'prerendered')
const SSR_PORT = 13714

async function main() {
    console.log('[Prerender] Starting static HTML prerendering...')

    const ssrBundlePath = path.join(process.cwd(), 'bootstrap', 'ssr', 'ssr.js')
    if (!fs.existsSync(ssrBundlePath)) {
        console.error('[Prerender] Error: SSR bundle not found at bootstrap/ssr/ssr.js. Run vite build --ssr first.')
        process.exit(1)
    }

    // Launch SSR server
    console.log('[Prerender] Spawning SSR server process...')
    const ssrProcess = spawn('node', [ssrBundlePath], {
        stdio: 'inherit',
        env: { ...process.env, PORT: SSR_PORT },
    })

    // Give SSR server time to start listening
    await new Promise(resolve => setTimeout(resolve, 2000))

    try {
        console.log('[Prerender] Fetching page targets and templates from Laravel...')
        execSync('php artisan prerender:data', { stdio: 'inherit' })
        const jsonPath = path.join(process.cwd(), 'storage', 'app', 'prerender_pages.json')
        if (!fs.existsSync(jsonPath)) {
            throw new Error(`File ${jsonPath} was not generated by php artisan prerender:data`)
        }
        const rawData = fs.readFileSync(jsonPath, 'utf-8')
        const pages = JSON.parse(rawData.trim())
        console.log(`[Prerender] Found ${pages.length} pages to prerender.`)

        let count = 0
        const failures = []
        for (const item of pages) {
            try {
                const ssrResult = await renderPage(item.page)
                const fullHtml = mergeHtml(item.htmlTemplate, ssrResult)

                const targetFile = path.join(PRERENDER_DIR, item.output)
                fs.mkdirSync(path.dirname(targetFile), { recursive: true })
                fs.writeFileSync(targetFile, fullHtml, 'utf-8')
                count++
            } catch (err) {
                failures.push({ url: item.url, error: err.message })
                console.warn(`[Prerender] Failed to render ${item.url}:`, err.message)
            }
        }

        console.log(`[Prerender] Successfully generated ${count}/${pages.length} static HTML pages in storage/app/prerendered/`)

        if (failures.length > 0) {
            throw new Error(`Prerendering failed for ${failures.length} page(s): ${failures.map(({ url }) => url).join(', ')}`)
        }
    } catch (err) {
        console.error('[Prerender] Error during prerender process:', err)
        process.exitCode = 1
    } finally {
        console.log('[Prerender] Terminating SSR server...')
        ssrProcess.kill('SIGTERM')
    }
}

function renderPage(pageObject) {
    return new Promise((resolve, reject) => {
        const payload = JSON.stringify(pageObject)
        const req = http.request(
            {
                hostname: '127.0.0.1',
                port: SSR_PORT,
                path: '/render',
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Content-Length': Buffer.byteLength(payload),
                },
            },
            res => {
                let data = ''
                res.on('data', chunk => (data += chunk))
                res.on('end', () => {
                    if (res.statusCode >= 200 && res.statusCode < 300) {
                        try {
                            resolve(JSON.parse(data))
                        } catch (e) {
                            reject(e)
                        }
                    } else {
                        reject(new Error(`HTTP ${res.statusCode}: ${data}`))
                    }
                })
            }
        )

        req.on('error', reject)
        req.write(payload)
        req.end()
    })
}

function mergeHtml(templateHtml, ssrResult) {
    let finalHtml = templateHtml

    if (ssrResult?.body) {
        // Replace <div id="app" data-page="..."></div> with rendered SSR body
        finalHtml = finalHtml.replace(/<div id="app"[^>]*>.*?<\/div>/s, ssrResult.body)
    }

    if (Array.isArray(ssrResult?.head) && ssrResult.head.length > 0) {
        const headTags = ssrResult.head.join('\n')
        finalHtml = finalHtml.replace('</head>', `${headTags}\n</head>`)
    }

    return finalHtml
}

main()
